apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysqldb
  template:
    metadata:
      labels:
        name: mysqldb
    spec:
      containers:
      - name: mysqldb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: somewordpress
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: wordpress
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql
---
################################
###   SERVICE SECTION       ####
################################
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    name: mysqldb
