apiVersion: v1
kind: Pod
metadata:
  name: gpod
spec:
  containers:
    - name: gpod
      image: gcr.io/google-samples/hello-app:1.0
      ports:
      - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 80 # modificar al puerto 8080 para que funcione
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"